#!/usr/bin/env python3
# This file is placed in the Public Domain.


import doctest
import inspect
import os
import shutil
import sys
import unittest


sys.path.insert(0, os.getcwd())


from bot.kernel import Config, boot
from bot.function import format
from bot.object import Object, values
from bot.parse import parse


import bot.all


Config.workdir = ".test"


flags = doctest.REPORT_NDIFF | doctest.FAIL_FAST | doctest.ELLIPSIS
results = []


def main():
    if os.path.exists(Config.workdir):
        shutil.rmtree(Config.workdir)
    boot(" ".join(sys.argv[1:]))
    Config.debug = True
    pat = "test_%s*" % "*"
    suite = unittest.loader.TestLoader().discover("test", pattern=pat)
    unittest.TextTestRunner(verbosity=3).run(suite)
    if Config.verbose:
        for txt in results:
            print(txt)


main()
