#!/usr/bin/env python3
# This file is placed in the Public Domain.


import doctest
import inspect
import os
import shutil
import sys
import unittest


sys.path.insert(0, os.getcwd())


from bot.krn import Cfg, boot
from bot.fnc import format
from bot.obj import Object, values
from bot.prs import parse
from bot.tbl import scan


import bot.all
import bot.mod.all


Cfg.wd = ".test"


flags = doctest.REPORT_NDIFF | doctest.FAIL_FAST | doctest.ELLIPSIS
results = []


def main():
    if os.path.exists(Cfg.wd):
        shutil.rmtree(Cfg.wd)
    boot(" ".join(sys.argv[1:]))
    Cfg.debug = True
    scan()
    pat = "test_%s*" % "*"
    suite = unittest.loader.TestLoader().discover("test", pattern=pat)
    unittest.TextTestRunner(verbosity=3).run(suite)
    if Cfg.verbose:
        for txt in results:
            print(txt)


main()
