#!/bin/ksh
# This file is placed in the Public Domain.

daemon="/usr/local/bin/botd"
daemon_flags=

. /etc/rc.d/rc.subr

rc_start() {
        ${rcexec} "${daemon} ${daemon_flags} 2>&1 &"
}

rc_stop() {
        ${rcexec} "pkill -9 -f botd &"
}

rc_cmd $1 
