name: botlib # you probably want to 'snapcraft register <name>'
version: '18' # just for humans, typically '1.2+git' or '1.3.2'
summary: Framework to program bots # 79 char long summary
description: |

  BOTLIB is a python3 framework to use if you want to program CLI, IRC or XMPP bots.

  Object class          - save/load to/from a JSON file.
  ReST server           - serve saved object’s over HTTP.
  RSS fetcher           - echo rss feeds to IRC channels.
  UDP server            - udp to bot to IRC channel.
  Watcher server        - run tail -f and have output send to IRC channel.
  Email scanning        - scan mbox format to searchable BOTLIB objects.
  JSON backend          - objects are stored as json string in files on the fs.
  Db                    - iteration over stored objects.
  Timestamp             - time based filenames gives logging capabilities
  Future                - future sensors should provide entry to the logger.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  botlib:
    command: bot

parts:
  my-part:
    # See 'snapcraft plugins'
    plugin: nil
